-- 1. NAME칼럼을 대문자로 변경하여 비교하기
SELECT ANIMAL_ID,NAME FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'Dog'
AND UPPER(NAME) LIKE '%EL%'
ORDER BY NAME;

-- 2. NAME 칼럼을 소문자로 변경하여 비교하기
SELECT ANIMAL_ID,NAME FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'Dog'
AND LOWER(NAME) LIKE '%el%'
ORDER BY NAME;
